config/routes.rb
Rails.application.routes.draw do
  get 'shopping_list/show', to: 'shopping_lists#show'
  get 'test', to: 'test#index'
  resources :ingredient_categories
  resources :ingredients
  devise_for :users

  authenticated :user do
    root 'landing#index', as: :authenticated_root
  end
  root 'static_pages#home'
  resources :scheduled_meals do
    collection do
      post 'attach_suggested_meal'
    end
  end

  post '/meals/tag', to: 'meals#tag'
  delete '/meals/untag', to: 'meals#untag'
  resources :meals
  resources :tags
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'whats_new', to: 'static_pages#whats_new'
  get 'feedback/new', to: 'static_pages#feedback_new'
  post 'feedback', to: 'static_pages#feedback_post'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  include PgSearch::Model

  attr_accessor :global_ingredient

  validates :name, presence: true

  belongs_to :ingredient_category, optional: true
  belongs_to :user, optional: true
  has_and_belongs_to_many :meals

  pg_search_scope :ingredient_search, against: :name, using: {:tsearch => {:prefix => true}}
  scope :ingredients_for, ->(user) {
    left_outer_joins(:user)
      .where("users.id = ? OR users.id is null", user.id)
  }

  def global?
    self.user.nil?
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
    respond_to do |format|
      format.html { @ingredients = Ingredient.ingredients_for(current_user).order(name: :asc) }
      format.json do
        ingredient_only_clause = "coalesce(ingredients.ingredient_category_id, 0) != #{USER_ITEM.id}" if params.fetch("ingredients_only", 0)
        if params.fetch(:term, "").empty?
          @ingredients = Ingredient.ingredients_for(current_user).
            where(ingredient_only_clause).
            select("ingredients.id as value", "ingredients.name as label", "'' as tag").order(label: :asc).all
        else
          @ingredients = Ingredient.ingredients_for(current_user).
            ingredient_search(params[:term]).
            where(ingredient_only_clause).
            select("ingredients.id as value", "ingredients.name as label").order(label: :asc).all
        end
        render json: @ingredients
      end
    end
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
    @ingredient_categories = IngredientCategory.all
  end

  def edit
    @ingredient_categories = IngredientCategory.all
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    unless ingredient_params[:global_ingredient] == '1' && current_user.user_type == 'admin'
      @ingredient.user = current_user
    end

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        @ingredient_categories = IngredientCategory.all
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if current_user.user_type != 'admin' and @ingredient.user != current_user
        redirect_to ingredients_path, notice: 'Unauthorized Action'
        return
      end
      if @ingredient.update(ingredient_params)
        if current_user.user_type == 'admin'
          if ingredient_params[:global_ingredient] == '1'
            @ingredient.user = nil
          else
            @ingredient.user = current_user
          end
          @ingredient.save
        end
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        @ingredient_categories = IngredientCategory.all
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if  current_user.user_type == 'admin' || @ingredient&.user == current_user
      @ingredient.destroy
      respond_to do |format|
        format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to ingredients_path, alert: 'Unable to remove ingredient.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.ingredients_for(current_user).find(params[:id])
    @ingredient.global_ingredient = true if @ingredient.user.nil?
  rescue ActiveRecord::RecordNotFound
    redirect_to ingredients_path, alert: "Ingredient not found"
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :ingredient_category_id, :global_ingredient)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :ingredient_category, class: "label" %>
    <div class="control">
      <div class="select">
        <%= form.select :ingredient_category_id, options_from_collection_for_select(@ingredient_categories, :id, :name, selected: ingredient.ingredient_category_id), {include_blank: true} %>
      </div>
    </div>
  </div>

  <% if current_user.user_type == 'admin' %>
    <div class="field">
      <div class="control">
      <%= form.label :global_ingredient?, class: "checkbox" %>
        <%= form.check_box :global_ingredient, class: "checkbox" %>
      </div>
    </div>
  <% end %>

  <div class="field is-grouped">
    <div class="control">
      <button class="button is-link">Save Ingredient</button>
    </div>
    <div class="control">
      <%= link_to 'Cancel', ingredients_path, class: "button is-link is-light" %>
    </div>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h2 class="subtitle is-2">Editing Ingredient</h2>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="subtitle is-2">Ingredients</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <% if current_user.user_type == 'admin'%>
        <th>Global</th>
      <% end %>
      <th>Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient.name, ingredient %></td>
        <% if current_user.user_type == 'admin'%>
          <td><%= ingredient.global? ? 'Yes' : 'No'  %></td>
        <% end %>
        <td> <%= ingredient.ingredient_category&.name %></td>
        <% if current_user.user_type == 'admin' || ingredient.user == current_user%>
          <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <% end %>
        <% if current_user.user_type == 'admin' || ingredient.user == current_user%>
          <td><%= link_to 'Remove', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h2 class="subtitle is-2">New Ingredient</h2>

<%= render 'form', ingredient: @ingredient %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Ingredient Category:</strong>
  <% if @ingredient.ingredient_category %>
    <%= @ingredient.ingredient_category.name %>
  <% else %>
    Not Specified
  <% end %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>