config/routes.rb
Rails.application.routes.draw do
  get 'shopping_list/show', to: 'shopping_lists#show'
  get 'test', to: 'test#index'
  resources :ingredient_categories
  resources :ingredients
  devise_for :users

  authenticated :user do
    root 'landing#index', as: :authenticated_root
  end
  root 'static_pages#home'
  resources :scheduled_meals do
    collection do
      post 'attach_suggested_meal'
    end
  end

  post '/meals/tag', to: 'meals#tag'
  delete '/meals/untag', to: 'meals#untag'
  resources :meals
  resources :tags
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'whats_new', to: 'static_pages#whats_new'
  get 'feedback/new', to: 'static_pages#feedback_new'
  post 'feedback', to: 'static_pages#feedback_post'
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
  validates :name, presence: true
end

app/controllers/ingredient_categories_controller.rb
class IngredientCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin
  before_action :set_ingredient_category, only: [:show, :edit, :update, :destroy]

  def index
    @ingredient_categories = IngredientCategory.all
  end

  def show
  end

  def new
    @ingredient_category = IngredientCategory.new
  end

  def edit
  end

  def create
    @ingredient_category = IngredientCategory.new(ingredient_category_params)

    respond_to do |format|
      if @ingredient_category.save
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient_category }
      else
        format.html { render :new }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ingredient_category.update(ingredient_category_params)
        format.html { redirect_to @ingredient_category, notice: 'Ingredient category was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient_category }
      else
        format.html { render :edit }
        format.json { render json: @ingredient_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ingredient_category.destroy
    respond_to do |format|
      format.html { redirect_to ingredient_categories_url, notice: 'Ingredient category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_ingredient_category
    @ingredient_category = IngredientCategory.find(params[:id])
  end

  def ingredient_category_params
    params.require(:ingredient_category).permit(:name, :icon_identifier, :accent_color)
  end

  def admin?
    current_user.user_type == 'admin'
  end

  def ensure_admin
    redirect_to root_url, notice: 'Unauthorized Action' and return unless admin?
  end
end

app/helpers/ingredient_categories_helper.rb
module IngredientCategoriesHelper
end

app/views/ingredient_categories/_form.html.erb
<%= form_with(model: ingredient_category, local: true) do |form| %>
  <% if ingredient_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient_category.errors.count, "error") %> prohibited this ingredient_category from being saved:</h2>

      <ul>
        <% ingredient_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :icon_identifier, class: "label" %>
    <%= form.text_field :icon_identifier, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :accent_color, class: "label" %>
    <%= form.text_field :accent_color, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-small is-primary" %>
  </div>
<% end %>

app/views/ingredient_categories/edit.html.erb
<h1>Editing Ingredient Category</h1>

<%= render 'form', ingredient_category: @ingredient_category %>

<%= link_to 'Show', @ingredient_category %> |
<%= link_to 'Back', ingredient_categories_path %>

app/views/ingredient_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredient Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredient_categories.each do |ingredient_category| %>
      <tr>
        <td><%= ingredient_category.name %></td>
        <td><%= link_to 'Show', ingredient_category %></td>
        <td><%= link_to 'Edit', edit_ingredient_category_path(ingredient_category) %></td>
        <td><%= link_to 'Remove', ingredient_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient Category', new_ingredient_category_path %>

app/views/ingredient_categories/new.html.erb
<h1>New Ingredient Category</h1>

<%= render 'form', ingredient_category: @ingredient_category %>

<%= link_to 'Back', ingredient_categories_path %>

app/views/ingredient_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient_category.name %>
</p>

<p>
  <strong>Icon identifier:</strong>
  <%= @ingredient_category.icon_identifier%>
  <i class="<%= @ingredient_category.icon_identifier %>"></i>
</p>

<p style="background-color: <%= @ingredient_category.accent_color %>;">
  <strong>Accent Color:</strong>
  <%= @ingredient_category.accent_color%>
</p>
<%= link_to 'Edit', edit_ingredient_category_path(@ingredient_category) %> |
<%= link_to 'Back', ingredient_categories_path %>