config/routes.rb
Rails.application.routes.draw do
  get 'shopping_list/show', to: 'shopping_lists#show'
  get 'test', to: 'test#index'
  resources :ingredient_categories
  resources :ingredients
  devise_for :users

  authenticated :user do
    root 'landing#index', as: :authenticated_root
  end
  root 'static_pages#home'
  resources :scheduled_meals do
    collection do
      post 'attach_suggested_meal'
    end
  end

  post '/meals/tag', to: 'meals#tag'
  delete '/meals/untag', to: 'meals#untag'
  resources :meals
  resources :tags
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'whats_new', to: 'static_pages#whats_new'
  get 'feedback/new', to: 'static_pages#feedback_new'
  post 'feedback', to: 'static_pages#feedback_post'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield :title %> | DnnrPcker </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'static_pages.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'autocomplete.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'shopping_list.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">

      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <h1 class="title">DnnrPckr</h1>
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'Home', root_path, class: "navbar-item" %>
          <% if user_signed_in? %>
            <%= link_to 'Meals', meals_path, class: "navbar-item" %>
            <% if current_user.user_type == 'admin' %>
              <%= link_to 'Tags', tags_path, class: "navbar-item" %>
              <%= link_to 'Ingredients', ingredients_path, class: "navbar-item" %>
              <%= link_to 'Ingredient Categories', ingredient_categories_path, class: "navbar-item" %>
            <% end %>
            <%= link_to 'Shopping List', shopping_list_show_path, class: "navbar-item" %>
            <%= link_to 'Profile', edit_user_registration_path, class: "navbar-item" %>
            <%= link_to 'Feedback', feedback_new_path, class: "navbar-item" %>
            <%= link_to "What's New!", whats_new_path, class: "navbar-item" %>
          <% end %>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
              <%= link_to('Log out', destroy_user_session_path, method: :delete, class: "button is-light") %>
              <% else %>
              <%= link_to('Sign up', new_user_registration_path, class: "button is-primary") %>
              <%= link_to('Log in', new_user_session_path, class: "button is-light") %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <% if notice %>
    <div class="message is-success">
      <p class="message-body"><%= notice %></p>
    </div>
    <% end %>
    <% if alert %>
    <div class="message is-warning">
      <p class="message-body"><%= alert %></p>
    </div>
    <% end %>
    <div class="section">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>